0928/class_0928/class0928App/urls.py
from django.urls import path
from . import views

"""
메인(R) : 게시글의 목록(/posts/) / 게시글 상세
작성(C) : 글을 작성하는 페이지(/posts/new/) / 작성 완료
수정(U) : 글을 수정하는 페이지 / 수정 완료
삭제(D) : 글 삭제 완료
"""

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name = 'new'),
    path('create/', views.create, name='create'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

0928/class_0928/class_0928/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('class0928App/', include('class0928App.urls')),
    path('practice0928App/', include('practice0928App.urls')),
]

0928/class_0928/practice0928App/urls.py
from django.urls import path
from . import views

# url namespace
# url을 이름으로 분류하는 기능
app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/<int:todo_pk>', views.delete, name='delete'),
    path('<int:todo_pk>/completed/', views.completed, name='completed'),
]

0928/class_0928/class0928App/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()

0928/class_0928/practice0928App/models.py
from email.policy import default
from pyexpat import model
from django.db import models

# Create your models here.

class Todo(models.Model):
    # django에서 pk(id)는 자동으로 만들어짐
    # 즉 id를 정의해줄 필요가 없음
    content = models.CharField(max_length=80)

    # defalut : 데이터를 생성할 때 값을 넣지 않으면
    # 자동으로 값을 채워서 데이터를 생성 하겠다는 의미
    completed = models.BooleanField(default=False)

    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

0928/class_0928/class0928App/views.py
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.

def index(request):
    # 모든 글 목록을 보여줌
    # DB에서 모든 글을 불러옴
    posts = Post.objects.all()

    # template에 보냄
    context = {
        'posts' : posts,
    }
    return render(request, 'posts/index.html', context)

def new(request):
    return render(request, 'posts/new.html')

def create(request):
    # parameter로 날아온 데이터를 받아서 
    title = request.GET.get('title')
    content = request.GET.get('content')

    # DB에 저장
    Post.objects.create(title=title, content=content)

    context = {
        'title' : title,
        'content' : content,
    }
    return redirect('posts:index')

def delete(request, pk):
    # pk에 해당하는 글 삭제
    Post.objects.get(id=pk).delete()

    return redirect('posts:index')

0928/class_0928/practice0928App/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.

def index(request):
    todos = Todo.objects.all().order_by('id')
    context = {
        'todos' : todos,
    }
    return render(request, 'todos/index.html', context)

def create(request):
    content = request.GET.get('content')
    priority = request.GET.get('priority')
    created_at = request.GET.get('created_at')
    deadline = request.GET.get('deadline')
    Todo.objects.create(content=content, priority=priority, deadline=deadline, created_at=created_at)

    return redirect('todos:index')

def delete(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk).delete()
    return redirect('todos:index')

def completed(request, todo_pk):
    update = Todo.objects.get(pk=todo_pk)
    update.completed = True
    update.save()
    return redirect('todos:index')

0928/class_0928/class0928App/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h1>작성 완료</h1>
<p>제목 : {{ title }}</p>
<p>내용 : {{ content }}</p>
<a href="{% url 'posts:index' %}">글 목록</a>
{% endblock %}

0928/class_0928/class0928App/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h1>게시판</h1>
<ul>
    {% for post in posts %}
    <li>ID : {{ post.id }} | 제목 : {{ post.title }} | 내용 : {{ post.content}}
        <a href="">수정</a>
        <a href="/posts/delete/{{ post.id }}">삭제</a>
    </li>
    {% endfor %}
</ul>
<a href="{% url 'posts:new' %}">새 글 쓰기</a>
{% endblock %}

0928/class_0928/class0928App/templates/posts/new.html
{% extends 'base.html' %}

{% block content %}
<h1>새 글 쓰기</h1>
<form action="{% url 'posts:create' %}">
    제목 : <input type="text" name="title">
    내용 : <input type="text" name="content">
    <input type="submit">
</form>
{% endblock %}