1012/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # 회원 가입 페이지
    # http://127.0.0.1:8000/accounts/signup/
    path('signup/', views.signup, name='signup'),
    # 회원 조회 페이지 (프로필)
    # http://127.0.0.1:8000/accounts/<user_pk>/
    path('detail/<int:pk>', views.detail, name='detail'),
    # 로그인
    path('login/', views.login, name='login'),
    # 로그아웃
    path('logout/', views.logout, name='logout'),
]

1012/accounts/forms.py
from dataclasses import fields
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

1012/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('accounts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/signup.html', context)

def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        'user' : user
    }
    return render(request, 'accounts/detail.html', context)

def login(request):
    if request.method == 'POST':
        # AuthenticationForm은 ModelForm이 아님
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                # 세션에 저장
                # login 함수는 request, user 객체를 인자로 받음
                # user 객체는 form에서 인증된 우저 정보를 받을 수 있음
                auth_login(request, form.get_user())
                return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('articles:index')

1012/accounts/templates/accounts/accounts.html
<!-- 회원 목록 페이지 -->

{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <div class="col-lg-9 col-md-12 px-5 mb-3">
    <table class="table">
      <thead class='table-light'>
        <tr>
          <th>번호</th>
          <th>사용자 이름</th>
          <th>이메일</th>
        </tr>
      </thead>
      <tbody class='table-group-divider'>
        {% for account in accounts %}
          <tr>
            <th>{{ account.pk }}</th>
            <th>
              <a href="{% url 'accounts:detail' account.pk %}">{{ account.username }}</a>
            </th>
            <th>{{ account.email }}</th>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock body %}

1012/accounts/templates/accounts/detail.html
<!-- 회원 조회 페이지 (프로필) -->

{% extends 'base.html' %}

{% block body %}
  <h1>프로필</h1>
  <div class="mb-3 mt-3">
    <label for="userpk" class="form-label">번호</label>
    <p name="content" id="userpk" class="form-control" disabled="disabled" readonly="readonly">{{ user.pk }}</p>
  </div>
  <div class="mb-3">
    <label for="username" class="form-label">사용자 이름</label>
    <p name="content" id="username" class="form-control" disabled="disabled" readonly="readonly">{{ user.username }}</p>
  </div>
  <div class="mb-3">
    <label for="useremail" class="form-label">이메일</label>
    <p name="content" id="useremail" class="form-control" disabled="disabled" readonly="readonly">{{ user.email }}</p>
  </div>
{% endblock body %}

1012/accounts/templates/accounts/index.html
<!-- 메인 페이지 -->

{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <a href="{% url 'accounts:signup' %}" class="text-white text-decoration-none text-center">
    <button class="btn btn-primary d-flex flex-column mt-3 col-12">회원 가입</button>
  </a>
  <a href="{% url 'accounts:accounts' %}" class="text-white text-decoration-none">
    <button class="btn btn-primary d-flex flex-column mt-3 col-12">회원 목록</button>
  </a>
{% endblock %}

1012/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>로그인</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
  </form>
{% endblock body %}

1012/accounts/templates/accounts/signup.html
<!-- 회원 가입 페이지 -->

{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>회원가입</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="가입하기" %}
  </form>
{% endblock body %}