1006/movie/urls.py
from unicodedata import name
from django import views
from django.urls import path
from . import views

app_name = 'movie'

urlpatterns = [
    # 영화 데이터 목록 조회
    path('', views.movies, name='movies'),

    # 영화 데이터 정보 조회
    path('<int:pk>/', views.detail, name='detail'),

    # 영화 데이터 생성
    path('create/', views.create, name='create'),

    # 영화 데이터 수정
    path('<int:pk>/update/', views.update, name='update'),

    # 영화 데이터 삭제
    path('<int:pk>/delete/', views.delete, name='delete'),
]

1006/movie/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50)
    summary = models.TextField()
    running_time = models.IntegerField()

1006/movie/views.py
from django.shortcuts import redirect, render
from .models import Movie
from .form import MovieForm

# Create your views here.

# 영화 데이터 목록 조회
def movies(request):
    movies = Movie.objects.all()
    context = {
        'movies' : movies
    }
    return render(request, 'movies/movies.html', context)

# 영화 데이터 정보 조회
def detail(request, pk):
    movies = Movie.objects.get(pk=pk)
    context = {
        'movies' : movies
    }
    return render(request, 'movies/detail.html', context)

# 영화 데이터 생성
def create(request):
    if request.method == 'POST':
        movies_form = MovieForm(request.POST)
        
        if movies_form.is_valid():
            movies_form.save()
            return redirect('movie:movies')
    
    else:
        movies_form = MovieForm()
    
    context = {
        'movies_form' : movies_form
    }
    return render(request, 'movies/form.html', context=context)

# 영화 데이터 수정
def update(request, pk):
    movie = Movie.objects.get(pk=pk)

    if request.method == 'POST':
        movies_form = MovieForm(request.POST, instance=movie)

        if movies_form.is_valid():
            movies_form.save()
            return redirect('movie:detail', movie.pk)

    else:
        movies_form = MovieForm(instance=movie)
    
    context = {
        'movies_form' : movies_form
    }
    return render(request, 'movies/form.html', context)

# 영화 데이터 삭제
def delete(request, pk):
    Movie.objects.get(pk=pk).delete()
    return redirect('movies:movie')

1006/movie/templates/movies/create.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

<!-- nav -->
<nav class="navbar navbar-light navbar-expand-lg">
  <div class="container-fluid">
    <!-- logo -->
    <a href="{% url 'movie:movies' %}" class="navbar-brand">
      <img src="{% static 'images/logo.png' %}" alt="logo" width="100" height="100" class="border border-gray rounded-3">
    </a>

    <!-- list -->
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active fs-5" aria-current="page" href="{% url 'movie:movies' %}">목록</a>
        <a class="nav-link active fs-5" href="{% url 'movie:create' %}">추가</a>
      </div>
    </div>
  </nav>
  <hr>

  <!-- body -->
  <h1 class="container text-center">작성하기</h1>
  <div class="container text-center">
    <form action="{% url 'movie:movies' %}" class="form-control  border border-white">
      {% csrf_token %}
      {% bootstrap_form movies_form %}
      <input type="submit" value="등록" class="btn btn-outline-secondary text-dark">
    </form>
  </div>

1006/movie/templates/movies/detail.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

<nav class="navbar navbar-light navbar-expand-lg">
  <div class="container-fluid">
    <!-- logo -->
    <a href="{% url 'movie:movies' %}" class="navbar-brand">
      <img src="{% static 'images/logo.png' %}" alt="logo" width="100" height="100" class="border border-gray rounded-3">
    </a>

    <!-- list -->
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active fs-5" aria-current="page" href="{% url 'movie:movies' %}">목록</a>
        <a class="nav-link active fs-5" href="{% url 'movie:create' %}">추가</a>
      </div>
    </div>
  </nav>
  <hr>

  <div class="container">
    <p>{{ movie.content }}</p>
  </div>

  <div class="container d-flex justify-content-end"></div>

1006/movie/templates/movies/form.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

<!-- nav -->
<nav class="navbar navbar-light navbar-expand-lg">
  <div class="container-fluid">
    <!-- logo -->
    <a href="{% url 'movie:movies' %}" class="navbar-brand">
      <img src="{% static 'images/logo.png' %}" alt="logo" width="100" height="100" class="border border-gray rounded-3">
    </a>

    <!-- list -->
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active fs-5" aria-current="page" href="{% url 'movie:movies' %}">목록</a>
        <a class="nav-link active fs-5" href="{% url 'movie:create' %}">추가</a>
      </div>
    </div>
  </nav>
  <hr>

  <!-- body -->
  <!-- <h1 class="container text-center">작성하기</h1> -->

  <div class="container text-center">
    {% if request.path == '/create/' %}
      <h1>작성하기</h1>
    {% elif request.path == '/update/' %}
      <h1>수정하기</h1>
    {% endif %}
    <form action="{% url 'movie:movies' %}" class="form-control  border border-white" method="POST">
      {% csrf_token %}
      {% bootstrap_form movies_form %}
      <input type="submit" value="등록" class="btn btn-outline-secondary text-dark">
    </form>
  </div>

1006/movie/templates/movies/movies.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

<!-- nav -->
<nav class="navbar navbar-light navbar-expand-lg">
  <div class="container-fluid">
    <!-- logo -->
    <a href="{% url 'movie:movies' %}" class="navbar-brand">
      <img src="{% static 'images/logo.png' %}" alt="logo" width="100" height="100" class="border border-gray rounded-3">
    </a>

    <!-- list -->
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active fs-5" aria-current="page" href="{% url 'movie:movies' %}">목록</a>
        <a class="nav-link active fs-5" href="{% url 'movie:create' %}">추가</a>
      </div>
    </div>
  </nav>
  <hr>

  <!-- body -->
  <div class="container">
    <table class="table text-center align-middle">
      <thead>
        <tr>
          <th>pk</th>
          <th>제목</th>
        </tr>
      </thead>
      <tbody>
        {% for movie in movies %}
          <a href="{% url 'movie:detail' movie.pk %}">
            <h4>{{ movie.title }}</h4>
          </a>
        {% endfor %}
      </tbody>
    </table>
  </div>