1026/PJT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

1026/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password/', views.change_password, name='change_password'),
    path('<int:pk>/', views.detail, name='detail'),
    path('update/', views.update, name='update'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

1026/articles/urls.py
from urllib.parse import urlparse
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:pk>/like/', views.like, name='like'),
]

1026/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(
        blank=True,
        processors=[Thumbnail(250, 250)],
        format='JPEG',
        options={'quality' : 100},
    )

1026/articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill, Thumbnail
from django.conf import settings

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to = 'images/',
        blank = True,
        processors=[ResizeToFill(500, 500)],
        format='JPEG',
        options={'quality' : 100},
    )
    thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(300, 300)],
        format='JPEG',
        options={'quality' : 100},
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default='')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=1000)

1026/accounts/forms.py
from django import forms
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Profile
from django import forms

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', )

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', )

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

1026/accounts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import CustomUserChangeForm, CustomUserCreationForm, ProfileForm
from .models import Profile
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required


# Create your views here.
# 회원 가입
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        profile = Profile()
        if form.is_valid():
            user = form.save()
            profile.user = user
            profile.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/signup.html', context)

# 로그인
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context)

# 로그아웃
def logout(request):
    auth_logout(request)
    return redirect('articles:index')

# 비밀번호 변경
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form' : form
    }
    return render(request, 'accounts/change_password.html', context)

# 회원 정보
@login_required
def detail(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    context = {
        'user' : user,
    }
    return render(request, 'accounts/detail.html', context)

# 회원 정보 수정
@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form
    }
    return render(request, 'accounts/update.html', context)

# 프로필
def profile(request):
    user = request.user
    articles = user.article_set.all()
    comments = user.comment_set.all()
    profile = user.profile_set.all()[0]
    context = {
        'articles' : articles,
        'comments' : comments,
        'profile' : profile,
    }
    return render(request, 'accounts/profile.html', context)

# 프로필 수정
@login_required
def profile_update(request):
    user = get_user_model().objects.get(pk=request.user.pk)
    current_user = user.profile_set.all()[0]
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = ProfileForm(instance=current_user)
    context = {
        'profile_form' : form,
    }
    return render(request, 'accounts/profile_update.html', context)

# 팔로우
@login_required
def follow(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    if request.user in user.followers.all():
        user.followers.remove(request.user)
    else:
        user.followers.add(request.user)
    return redirect('accounts:detail', pk)

1026/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>비밀번호 변경</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit">수정하기</button>
    <button class="btn btn-light" type="button" onclick="location.href='{% url 'articles:index' %}">돌아가기</button>
  </form>
{% endblock content %}

1026/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="d-flex align-items-center">
    <div>
      {% if profile.image %}
        <img src="{{ profile.image.url }}" alt="" style="width: 100px; height: 100px; border-radius: 500px">
      {% else %}
        <img src="https://i.pinimg.com/originals/f1/5c/9e/f15c9e2ce52a1735081be72dcec2e97d.jpg" alt="" style="width: 100px; height: 100px; border-radius: 500px">
      {% endif %}
    </div>
    <div>
      <div class="d-flex align-items-center">
        <h1 class="mx-3">{{ user.username }}</h1>
        <div>
          {% if request.user != user %}
            <a href="{% url 'accounts:follow' user.pk %}" class="btn btn-light">
              {% if request.user in user.followers.all %}
                팔로잉
              {% else %}
                팔로우
              {% endif %}
            </a>
          {% endif %}
        </div>
      </div>
      <div class="d-flex mx-3">
        <div class="mx-1">
          팔로워
          {{ user.followers.count }}
        </div>
        <div class="mx-1">
          팔로우
          {{ user.followings.count }}
        </div>
      </div>
    </div>
  </div>

  <div class="d-flex justify-content-between">
    <div class="col-6">
      <p class="mt-3">작성한 게시글 :
        {{ user.article_set.count }}개</p>
      {% for article in user.article_set.all %}
        {% if article.image %}
          <div class="row">
            <a href="{% url 'articles:detail' article.pk %}">
              <p class="thumbimg">
                <img src="{{ article.thumbnail.url }}" alt="{{ article.image }}">
              </p>
              <p>{{ article.title }}</p>
            </a>
          </div>
        {% endif %}
      </div>
    {% endfor %}
    <div class="col-6">
      <div>
        <p class="mt-3">작성한 댓글 :
          {{ user.comment_set.count }}개</p>
        {% for comment in user.comment_set.all %}
          <p>{{ forloop.counter }}
            <a href="{% url 'article:detail' comment.article_id %}">{{ comment.content }}</a>
          </p>
        {% endfor %}
      </div>
    </div>
  </div>
  <button class="btn btn-primary mt-5" type="submit" onclick="location.href='{% url 'articles:index' %}">돌아가기</button>
{% endblock content %}

1026/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>로그인</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit" onclick="location.href='{% url 'articles:index' %}">로그인</button>
  </form>
{% endblock content %}

1026/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="d-flex align-items-center">
    <div>
      {% if profile.image %}
        <img src="{{ profile.image.url }}" alt="" style="width: 100px; height: 100px; border-radius: 500px">
      {% else %}
        <img src="https://i.pinimg.com/originals/f1/5c/9e/f15c9e2ce52a1735081be72dcec2e97d.jpg" alt="" style="width: 100px; height: 100px; border-radius: 500px">
      {% endif %}
    </div>
    <div>
      <div class="d-flex align-items-center">
        <h1 class="mx-3">{{ user.username }}</h1>
        <div>
          <a href="{% url 'accounts:profile_update' %}" class="btn btn-light mx-3">프로필 수정</a>
        </div>
      </div>
      <div class="d-flex mx-3">
        <div class="mx-1">
          팔로워
          {{ user.followers.count }}
        </div>
        <div class="mx-1">
          팔로우
          {{ user.followings.count }}
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-between mt-5">
    <div class="col-4">
      <h3>작성한 글</h3>
      {% for article in articles %}
        <div>
          <p class="text-muted">{{ user.article_set.count }}개</p>
          <a href="{% url 'articles:detail' article.pk %}">
            <p>{{ article.title }}</p>
          </a>
        </div>
        {% empty %}
        <div>
          <p>작성한 글이 없습니다.</p>
        </div>
      {% endfor %}
    </div>
    <div class="col-4">
      <h3>작성한 댓글</h3>
      {% for comment in commnets %}
        <p class="text-muted">{{ user.comment_set.count }}개</p>
        <p>{{ comment.content }}</p>
        {% empty %}
        <p>작성한 댓글이 없습니다.</p>
      {% endfor %}
    </div>
    <div class="col-4">
      <h3>좋아요 한 글</h3>
      {% for article in user.like_articles.all %}
        <p>
          {{ forloop.counter }}
          <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
        </p>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

1026/accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>프로필 수정</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form profile_form %}
    <button class="btn btn-primary" type="submit">수정하기</button>
  </form>
{% endblock content %}

1026/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>회원가입</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit">가입하기</button>
  </form>
{% endblock content %}

1026/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>회원 정보 수정</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit">수정하기</button>
    <button class="btn btn-light" type="button" onclick="location.href='{% url 'articles:index' %}">돌아가기</button>
  </form>
{% endblock content %}